[build.environment]
  NODE_VERSION = "18"

[build]
  publish = "dist"
  command = "pnpm run build"

[[redirects]]
  from = "/sso/*"
  to = "https://login.sina.com.cn/sso/:splat"
  status = 200
  force = true
  headers = { Host = "login.sina.com.cn", Referer = "https://weibo.com/" }

[[redirects]]
  from = "/wbsso/*"
  to = "https://passport.weibo.com/wbsso/:splat"
  status = 200
  force = true
  headers = { Host = "login.sina.com.cn", Referer = "https://weibo.com/" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
