[build.environment]
NODE_VERSION = "18"

[build]
publish = "dist"
command = "pnpm run build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/sso"
to = "https://login.sina.com.cn/sso"
status = 200
force = true
headers = { Accept = '*/*', Sec-Ch-Ua = '"Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"', Sec-Ch-Ua-Mobile = '?0', Sec-Fetch-Dest = 'script', Sec-Fetch-Mode = 'no-cors', Sec-Fetch-Site = 'cross-site', User-Agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36', Accept-Encoding = 'gzip, deflate, br', Accept-Language = 'zh-CN,zh;q=0.9', Referer = 'https://weibo.com/', Sec-Ch-Ua-Platform = "Windows" }

[[redirects]]
from = "/wbsso"
to = "https://passport.weibo.com/wbsso"
status = 200
force = true
headers = { Accept = '*/*', Sec-Ch-Ua = '"Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"', Sec-Ch-Ua-Mobile = '?0', Sec-Fetch-Dest = 'script', Sec-Fetch-Mode = 'no-cors', Sec-Fetch-Site = 'cross-site', User-Agent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36', Accept-Encoding = 'gzip, deflate, br', Accept-Language = 'zh-CN,zh;q=0.9', Referer = 'https://weibo.com/', Sec-Ch-Ua-Platform = "Windows" }
